apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon-nats-deployment
  namespace: name-twin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falcon-nats
  template:
    metadata:
      labels:
        app: falcon-nats
    spec:
      containers:
        - name: falcon-nats
          image: nats:latest
          ports:
            - containerPort: 4222
---
apiVersion: v1
kind: Service
metadata:
  name: falcon-nats-svc
  namespace: name-twin
spec:
  selector:
    app: falcon-nats
  type: LoadBalancer # NodePort에서 LoadBalancer로 변경
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
