{{- $componentType := "distributor" }}
{{- with (index .Values $componentType) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $componentType }}
  labels:
    app: {{ $componentType }}
spec:
  selector:
    matchLabels:
      app: {{ $componentType }}
  template:
    metadata:
      labels:
        app: {{ $componentType }}
    spec:
      containers:
        - name: {{ .distributor_api.name }}
          image: {{ $.Values.imageRepository }}/{{ .distributor_api.image }}
          ports:
            - containerPort: {{ .distributor_api.port }}
          volumeMounts:
            - name: shared_storage
              mountPath: /shared

        - name: {{ .distributor_kafka.name }}
          image: {{ $.Values.imageRepository }}/{{ .distributor_kafka.image }}
          envFrom:
            {{- toYaml .distributor_kafka.envFrom | nindent 12 }}
          volumeMounts:
            - name: shared_storage
              mountPath: /shared

      volumes:
        - name: shared_storage
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .distributor_api.name }}-service
spec:
  type: {{ .distributor_api.type }}
  ports:
    - port: 8000
      targetPort: {{ .distributor_api.port }}
  selector:
    app: {{ .distributor_api.name }}

{{- end }}
