{{- $component_type := "distributor-kafka" }}
{{- with (index .Values $component_type) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ $.Values.imageRepository }}/{{ .image }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  type: {{ .type }}
  selector:
    app: {{ .name }}
{{- end }}
