{{- $component_type := "distributor-api" }}
{{- with (index .Values $component_type) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ $.Values.imageRepository }}/{{ .image }}
          ports:
            - containerPort: {{ .port }}
          volumeMounts:
          - name: shared-storage
            mountPath: /mnt/shared

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-service
spec:
  type: {{ .type }}
  ports:
    - port: 8000
      targetPort: {{ .port }}
  selector:
    app: {{ .name }}
{{- end }}
