imageRepository: minjuncho

distributor-api:
  name: falcon-distributor-api-helm
  image: falcon-distributor-api:3
  port: 8000
  replicas: 2
  type: LoadBalancer

blms-be-gpu:
  name: blms-transceiver-helm-gpu
  image: blms-transceiver:18
  port: 8000
  replicas: 1
  type: LoadBalancer
  # gpu_count: 1
  envFrom:
    - secretRef:
        name: blms-gpt-api-key-yaml
