imageRepository: minjuncho

distributor-api:
  name: blms-fe-helm
  image: blms-fe:4
  port: 8501
  replicas: 2
  type: ClusterIP

blms-be-gpu:
  name: blms-transceiver-helm-gpu
  image: blms-transceiver:18
  port: 8000
  replicas: 1
  type: LoadBalancer
  # gpu_count: 1
  envFrom:
    - secretRef:
        name: blms-gpt-api-key-yaml
