imageRepository: minjuncho

distributor_api:
  name: distributor-api-helm
  image: falcon-distributor-api:3
  port: 8000
  replicas: 2
  type: LoadBalancer

distributor_kafka:
  name: distributor-kafka-helm
  image: falcon-distributor-kafka:15
  replicas: 1
  envFrom:
    - secretRef:
        name: falcon-distributor-kafka-secret
