imageRepository: minjuncho

distributor-api:
  name: distributor-api-helm
  image: falcon-distributor-api:3
  port: 8000
  replicas: 2
  type: LoadBalancer

distributor-kafka:
  name: distributor-kafka-helm
  image: falcon-distributor-kafka:2
  port: 8000
  replicas: 1
  type: ClusterIP
