apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon-sub-deployment
  namespace: name-twin
  labels:
    app: falcon-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falcon-sub
  template:
    metadata:
      labels:
        app: falcon-sub
    spec:
      containers:
        - name: falcon-sub
          image: cjfgml0306/falcon-sub:latest
          env:
            - name: NATS_SERVER
              valueFrom:
                configMapKeyRef:
                  name: falcon-nats-config
                  key: nats_server
            - name: NATS_PORT
              valueFrom:
                configMapKeyRef:
                  name: falcon-nats-config
                  key: nats_port
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: falcon-nats-config
  namespace: name-twin
data:
  nats_server: "falcon-nats-svc"
  nats_port: "4222"
