apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcon-sub-deployment
  namespace: name-twin
  labels:
    app: falcon-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falcon-sub
  template:
    metadata:
      labels:
        app: falcon-sub
    spec:
      containers:
        - name: falcon-sub
          image: cjfgml0306/falcon-sub-demo:latest
          env:
            - name: NATS_SERVER
              valueFrom:
                configMapKeyRef:
                  name: falcon-sub-config
                  key: nats_server
            - name: NATS_PORT
              valueFrom:
                configMapKeyRef:
                  name: falcon-sub-config
                  key: nats_port
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: falcon-sub-config
                  key: kafka_broker
            - name: BROKER_PORT
              valueFrom:
                configMapKeyRef:
                  name: falcon-sub-config
                  key: broker_port
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: falcon-sub-config
  namespace: name-twin
data:
  nats_server: "10.48.24.83"
  nats_port: "4222"
  kafka_broker: "210.125.85.62"
  broker_port: "9094"
